### ISSUE TITLE
Not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by HarshitJoshi** [jliu2179/teleporter#2]
I get an error when I try to setup teleporter on my machine. I'm currently running Ubuntu 16.04 LTS Xenial Xerus:

```
/scripts/teleporter: line 13: syntax error near unexpected token 'fi'
/scripts/teleporter: line 13:    'fi'
```

**Comment by cliuj** [comment]
Hmm.. interesting. I've only ran this on my Arch setup, so I was not aware of this issue with Ubuntu 16.04 distro. This could be an issue with other distros as well, so thank you for letting me know. I'll mark this as a confirmed bug given your input.

**Comment by cliuj** [comment]
It seems that the `fi` issue is not present on my setup. I am able to run the script normally without any errors. Perhaps it's an environment issue?

**Comment by HarshitJoshi** [comment]
After some debugging, I was able to narrow it down to the if-else conditional checking in the teleporter script. I've managed to get it running on my machine now, I have a PR (#3) ready that resolves it. I've also added some lint to a few files. Also, to get it running I had to manually make it use `~/scripts` for now. (refer #1)

**Comment by cliuj** [comment]
This has been merged.
